Repository taewoo922/Coconut, pull requests merged in 2024-06, with the labels that each got.

#40 검색 페이지 중간 완료
  src/main/java/com/example/coconut/domain/report/controller/ReportController.java
  src/main/java/com/example/coconut/domain/report/entity/Report.java
  src/main/java/com/example/coconut/domain/report/form/ReportForm.java
  src/main/java/com/example/coconut/domain/report/repository/ReportRepository.java
  src/main/java/com/example/coconut/domain/report/service/ReportService.java
  src/main/java/com/example/coconut/domain/user/controller/UserController.java
  src/main/java/com/example/coconut/domain/user/service/UserService.java
  src/main/resources/static/css/navbarStyle.css
  src/main/resources/static/css/reportDetail.css
  src/main/resources/static/css/reportForm.css
  src/main/resources/static/css/reportList.css
  src/main/resources/static/css/user1.css
  src/main/resources/static/js/detailFunction.js
  src/main/resources/static/js/navbar.js
  src/main/resources/static/js/navbarFunction.js
  src/main/resources/static/js/report.js
  src/main/resources/static/js/user.js
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/common/navbar.html
  src/main/resources/templates/report/detail.html
  src/main/resources/templates/report/form.html
  src/main/resources/templates/report/list.html
  src/main/resources/templates/user/search.html
  src/test/java/com/example/coconut/CoconutApplicationTests.java
Labels: enhancement

#43 main, search page 내 게시물 가져오기 구현
  src/main/java/com/example/coconut/domain/discussion_Type/repository/FreedcsRepository.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/FreedcsService.java
  src/main/java/com/example/coconut/domain/home/controller/HomeController.java
  src/main/java/com/example/coconut/domain/user/controller/UserController.java
  src/main/java/com/example/coconut/domain/user/service/UserService.java
  src/main/resources/static/css/main.css
  src/main/resources/static/css/user1.css
  src/main/resources/static/js/user.js
  src/main/resources/templates/home/main.html
  src/main/resources/templates/user/search.html
  src/test/java/com/example/coconut/CoconutApplicationTests.java
Labels: enhancement

#45 footer, main, best_report, report list, initData nickname 수정
  src/main/java/com/example/coconut/domain/report/controller/ReportController.java
  src/main/java/com/example/coconut/domain/report/entity/Report.java
  src/main/java/com/example/coconut/domain/report/service/ReportService.java
  src/main/java/com/example/coconut/global/initData/Dev.java
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/reportDetail.css
  src/main/resources/static/css/user1.css
  src/main/resources/static/images/freeback.jpg
  src/main/resources/static/images/freebackImg.jpg
  src/main/resources/static/images/procon.jpg
  src/main/resources/static/images/slideImage_1.jpg
  src/main/resources/static/images/slideImage_2.jpg
  src/main/resources/static/images/slideImage_3.jpg
  src/main/resources/static/images/slideImage_7.jpg
  src/main/resources/static/images/slideImage_8.jpg
  src/main/resources/static/js/main.js
  src/main/resources/static/js/user.js
  src/main/resources/templates/common/footer.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/home/main.html
  src/main/resources/templates/report/best_report.html
  src/main/resources/templates/report/detail.html
  src/main/resources/templates/report/list.html
  src/main/resources/templates/user/search.html
  src/test/java/com/example/coconut/CoconutApplicationTests.java
Labels: enhancement

#46 Update README.md
  README.md
Labels: documentation

#49 search , report list 수정
  src/main/java/com/example/coconut/domain/report/controller/ReportController.java
  src/main/java/com/example/coconut/domain/report/entity/Report.java
  src/main/java/com/example/coconut/domain/report/form/ReportForm.java
  src/main/java/com/example/coconut/domain/report/service/ReportService.java
  src/main/resources/static/css/reportForm.css
  src/main/resources/static/js/search.js
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/report/form.html
  src/main/resources/templates/report/list.html
  src/main/resources/templates/user/search.html
Labels: enhancement

#54 소셜로그인 아이콘, 마이페이지 기본이미지 설정
  src/main/resources/static/default_profile_image.jpg
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
Labels: enhancement

#56 Update README.md
  README.md
Labels: documentation

#58 비속어 필터링
  build.gradle
  src/main/java/com/example/coconut/domain/ProfanityFilter.java
  src/main/java/com/example/coconut/domain/report/controller/ReportController.java
  src/main/java/com/example/coconut/domain/report/form/ReportForm.java
  src/main/resources/static/css/reportForm.css
  src/main/resources/templates/common/form_errors.html
  src/main/resources/templates/report/form.html
Labels: enhancement

#61 비속어, 공개, 비공개 alert 창 수정
  src/main/java/com/example/coconut/UnauthorizedAccessException.java
  src/main/java/com/example/coconut/domain/ProfanityFilter.java
  src/main/java/com/example/coconut/domain/report/controller/ReportController.java
  src/main/java/com/example/coconut/domain/report/service/ReportService.java
  src/main/resources/static/css/reportForm.css
  src/main/resources/static/css/reportList.css
  src/main/resources/static/images/freeback.jpg
  src/main/resources/static/js/report.js
  src/main/resources/templates/report/form.html
  src/main/resources/templates/report/list.html
Labels: enhancement

#62 프로필 수정 이미지 미리보기, html, css 정리
  src/main/java/com/example/coconut/domain/user/controller/UserController.java
  src/main/resources/static/css/login.css
  src/main/resources/static/css/profile.css
  src/main/resources/static/css/profile_edit.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/js/profile_edit.js
  src/main/resources/templates/user/edit-profile.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/signup.html
Labels: enhancement

#69 Update README.md
  README.md
Labels: documentation

#68 main page 수정
  src/main/java/com/example/coconut/domain/discussion_Type/repository/FreedcsRepository.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/FreedcsService.java
  src/main/java/com/example/coconut/domain/home/controller/HomeController.java
  src/main/java/com/example/coconut/domain/report/repository/ReportRepository.java
  src/main/java/com/example/coconut/domain/user/repository/UserRepository.java
  src/main/java/com/example/coconut/global/initData/Dev.java
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/reportDetail.css
  src/main/resources/static/css/user1.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/common/footer.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/home/main.html
  src/main/resources/templates/user/admin.html
  src/test/java/com/example/coconut/CoconutApplicationTests.java
Labels: enhancement

#72 report detail 수정
  src/main/resources/static/css/main.css
  src/main/resources/static/css/reportDetail.css
  src/main/resources/templates/common/.layout.html.swp
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/report/detail.html
  src/main/resources/templates/user/search.html
  src/main/resources/templates/user/signup.html
  src/test/java/com/example/coconut/CoconutApplicationTests.java
Labels: enhancement

#75 전체 토론 검색기능 구현중
  src/main/java/com/example/coconut/domain/discussion_Type/controller/SearchController.java
  src/main/java/com/example/coconut/domain/discussion_Type/repository/DebateRepository.java
  src/main/java/com/example/coconut/domain/discussion_Type/repository/FreedcsRepository.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/DebateService.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/FreedcsService.java
  src/main/resources/static/css/profile.css
  src/main/resources/templates/common/navbar.html
  src/main/resources/templates/discussion/search_results.html
  src/main/resources/templates/user/profile.html
Labels: enhancement

#77 검색 수정중
  src/main/resources/static/css/search.css
  src/main/resources/templates/discussion/search_results.html
  src/main/resources/templates/user/profile.html
Labels: enhancement

#80 토론페이지 수정
  src/main/java/com/example/coconut/domain/answer/controller/AnswerController.java
  src/main/java/com/example/coconut/domain/answer/service/AnswerService.java
  src/main/java/com/example/coconut/domain/discussion_Type/controller/DebateController.java
  src/main/java/com/example/coconut/domain/discussion_Type/controller/FreedcsController.java
  src/main/resources/static/css/debateDetail.css
  src/main/resources/static/css/freedcsDetail.css
  src/main/resources/static/js/debate.js
  src/main/resources/templates/common/.layout.html.swp
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/discussion/d_create_form.html
  src/main/resources/templates/discussion/d_detail.html
  src/main/resources/templates/discussion/debate_reply.html
  src/main/resources/templates/discussion/freedcs_reply.html
  src/main/resources/templates/home/main.html
Labels: enhancement

#82 검색페이지 수정
  src/main/java/com/example/coconut/domain/discussion_Type/controller/SearchController.java
  src/main/resources/static/css/search.css
  src/main/resources/static/js/d_search.js
  src/main/resources/templates/common/navbar.html
  src/main/resources/templates/discussion/search_results.html
  src/main/resources/templates/user/profile.html
Labels: enhancement

#84 Enhancement/81
  src/main/java/com/example/coconut/domain/answer/AnswerForm.java
  src/main/java/com/example/coconut/domain/discussion_Type/controller/DebateController.java
  src/main/java/com/example/coconut/domain/discussion_Type/controller/FreedcsController.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/DebateService.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/FreedcsService.java
  src/main/resources/static/css/debateDetail.css
  src/main/resources/static/css/freedcsList.css
  src/main/resources/static/css/navbarStyle.css
  src/main/resources/static/css/reportList.css
  src/main/resources/static/js/debate.js
  src/main/resources/static/js/freedcs.js
  src/main/resources/static/js/report.js
  src/main/resources/templates/common/navbar.html
  src/main/resources/templates/discussion/d_detail.html
  src/main/resources/templates/discussion/debate_list.html
  src/main/resources/templates/discussion/freedcs_list.html
  src/main/resources/templates/discussion/search_results.html
  src/test/java/com/example/coconut/CoconutApplicationTests.java
Labels: enhancement

#85 토론 페이지 thumbnail 기능 추가
  src/main/java/com/example/coconut/domain/discussion_Type/controller/DebateController.java
  src/main/java/com/example/coconut/domain/discussion_Type/controller/FreedcsController.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/DebateService.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/FreedcsService.java
  src/main/resources/static/css/debateDetail.css
  src/main/resources/static/js/freedcs.js
  src/main/resources/templates/common/navbar.html
  src/main/resources/templates/discussion/d_detail.html
  src/test/java/com/example/coconut/CoconutApplicationTests.java
Labels: enhancement

#94 내가 쓴 게시글 - 찬반, 메인 - 찬반, 최신 수정, qna - 관리자 접근 가능
  src/main/java/com/example/coconut/domain/discussion_Type/repository/DebateRepository.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/DebateService.java
  src/main/java/com/example/coconut/domain/home/controller/HomeController.java
  src/main/java/com/example/coconut/domain/report/service/ReportService.java
  src/main/java/com/example/coconut/domain/user/controller/UserController.java
  src/main/resources/static/css/main.css
  src/main/resources/static/css/user1.css
  src/main/resources/static/js/main.js
  src/main/resources/static/js/search.js
  src/main/resources/templates/home/main.html
  src/main/resources/templates/user/search.html
Labels: documentation

#96 회원탈퇴 추가
  src/main/java/com/example/coconut/domain/user/controller/UserController.java
  src/main/java/com/example/coconut/domain/user/service/UserService.java
  src/main/resources/static/css/profile_edit.css
  src/main/resources/static/js/profile_edit.js
  src/main/resources/templates/user/edit-profile.html
Labels: enhancement

#98 QnA nickname 사용변경
  src/main/java/com/example/coconut/domain/home/controller/HomeController.java
  src/main/java/com/example/coconut/domain/report/service/ReportService.java
  src/main/resources/templates/report/detail.html
  src/main/resources/templates/report/list.html
Labels: enhancement

#102 토론 페이지 nickname 추가, 필터링 main page 수정, 완료
  src/main/java/com/example/coconut/domain/answer/controller/AnswerController.java
  src/main/java/com/example/coconut/domain/discussion_Type/controller/DebateController.java
  src/main/java/com/example/coconut/domain/discussion_Type/controller/FreedcsController.java
  src/main/java/com/example/coconut/domain/discussion_Type/entity/Debate.java
  src/main/java/com/example/coconut/domain/discussion_Type/entity/Freedcs.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/DebateService.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/FreedcsService.java
  src/main/java/com/example/coconut/domain/report/controller/ReportController.java
  src/main/java/com/example/coconut/domain/reportReply/controller/ReportReplyController.java
  src/main/java/com/example/coconut/domain/user/entity/User.java
  src/main/resources/static/css/main.css
  src/main/resources/static/css/reportList.css
  src/main/resources/templates/discussion/d_create_form.html
  src/main/resources/templates/discussion/d_detail.html
  src/main/resources/templates/discussion/debate_list.html
  src/main/resources/templates/discussion/debate_reply.html
  src/main/resources/templates/discussion/free_create_form.html
  src/main/resources/templates/discussion/freedcs_detail.html
  src/main/resources/templates/discussion/freedcs_list.html
  src/main/resources/templates/discussion/freedcs_reply.html
  src/main/resources/templates/report/detail.html
  src/main/resources/templates/report/list.html
  src/main/resources/templates/report/reply_form.html
Labels: enhancement

#104 관리자페이지 디자인
  src/main/resources/static/css/admin.css
  src/main/resources/templates/manager/admin.html
  src/main/resources/templates/manager/debatelist.html
  src/main/resources/templates/manager/freedcslist.html
  src/main/resources/templates/manager/questionlist.html
Labels: enhancement

#107 토론 페이지 답변 공백 에러 메세지 수정
  src/main/java/com/example/coconut/domain/answer/controller/AnswerController.java
  src/main/resources/templates/user/search.html
Labels: enhancement

#109 뒤로가기 버튼 추가
  src/main/java/com/example/coconut/domain/user/controller/UserController.java
  src/main/java/com/example/coconut/domain/user/entity/User.java
  src/main/java/com/example/coconut/global/security/CustomOauth2UserDetails.java
  src/main/java/com/example/coconut/global/security/CustomOauth2UserService.java
  src/main/resources/static/css/login.css
  src/main/resources/static/css/profile.css
  src/main/resources/static/css/profile_edit.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/js/back.js
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/signup.html
Labels: enhancement

#110 토론 페이지 디자인
  src/main/resources/static/css/debateDetail.css
  src/main/resources/static/css/freedcsDetail.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/discussion/d_detail.html
Labels: enhancement

#113 Update README.md
  README.md
Labels: documentation

#119 Enhancement/118
  src/main/resources/static/css/common/main.css
  src/main/resources/static/css/common/navbarStyle.css
  src/main/resources/static/css/report/reportList.css
  src/main/resources/templates/common/footer.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/home/main.html
  src/test/java/com/example/coconut/CoconutApplicationTests.java
Labels: enhancement

#121 마이페이지, 프로필 수정 디자인 변경
  src/main/resources/static/css/user/profile.css
  src/main/resources/static/css/user/profile_edit.css
  src/main/resources/static/js/user/profile_edit.js
  src/main/resources/templates/user/edit-profile.html
  src/main/resources/templates/user/profile.html
Labels: enhancement

#125 네브바 스타일 수정, 질문 하기 수정, css 오류 수정
  src/main/java/com/example/coconut/domain/admin/controller/AdminController.java
  src/main/java/com/example/coconut/domain/report/controller/ReportController.java
  src/main/java/com/example/coconut/domain/report/entity/Report.java
  src/main/java/com/example/coconut/domain/report/repository/ReportRepository.java
  src/main/java/com/example/coconut/domain/report/service/ReportService.java
  src/main/resources/static/css/categoryform.css
  src/main/resources/static/css/common/navbarStyle.css
  src/main/resources/static/css/navbarStyle.css
  src/main/resources/static/css/report/baseReport.css
  src/main/resources/static/css/report/bestReport.css
  src/main/resources/static/css/report/reportDetail.css
  src/main/resources/static/css/report/reportList.css
  src/main/resources/static/css/user/admin.css
  src/main/resources/static/js/report/report.js
  src/main/resources/templates/category/category_manage.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/common/navbar.html
  src/main/resources/templates/discussion/freedcs_list.html
  src/main/resources/templates/report/base.html
  src/main/resources/templates/report/best_report.html
  src/main/resources/templates/report/detail.html
  src/main/resources/templates/report/list.html
Labels: bug, enhancement

#127 아이디찾기 / 비밀번호찾기 구현중
  src/main/java/com/example/coconut/domain/user/controller/UserController.java
  src/main/java/com/example/coconut/domain/user/repository/UserRepository.java
  src/main/java/com/example/coconut/domain/user/service/UserService.java
  src/main/resources/templates/user/find-username.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/reset-password.html
Labels: enhancement

#128 관리자 페이지 수정, 답변등록 버튼 수정
  src/main/java/com/example/coconut/domain/discussion_Type/service/DebateService.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/FreedcsService.java
  src/main/resources/static/css/categoryform.css
  src/main/resources/static/css/report/reportForm.css
  src/main/resources/static/css/report/reportList.css
  src/main/resources/static/css/user/admin.css
  src/main/resources/static/images/coconut.png
  src/main/resources/templates/category/category_manage.html
  src/main/resources/templates/manager/admin.html
  src/main/resources/templates/manager/debatelist.html
  src/main/resources/templates/manager/freedcslist.html
  src/main/resources/templates/manager/questionlist.html
  src/test/java/com/example/coconut/CoconutApplicationTests.java
Labels: enhancement

#130 토론페이지 css 변경
  src/main/java/com/example/coconut/domain/discussion_Type/service/DebateService.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/FreedcsService.java
  src/main/resources/static/css/discussion/debateDetail.css
  src/main/resources/static/css/discussion/freedcsDetail.css
  src/main/resources/static/css/discussion/freedcsList.css
  src/main/resources/templates/discussion/freedcs_detail.html
  src/test/java/com/example/coconut/CoconutApplicationTests.java
Labels: enhancement

#131 css 수정
  src/main/java/com/example/coconut/domain/discussion_Type/controller/FreedcsController.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/DebateService.java
  src/main/java/com/example/coconut/domain/discussion_Type/service/FreedcsService.java
  src/main/resources/static/css/categoryform.css
  src/main/resources/static/css/common/footer.css
  src/main/resources/static/css/common/main.css
  src/main/resources/static/css/common/navbarStyle.css
  src/main/resources/static/css/discussion/debateDetail.css
  src/main/resources/static/css/discussion/freedcsDetail.css
  src/main/resources/static/css/discussion/freedcsForm.css
  src/main/resources/static/css/discussion/freedcsList.css
  src/main/resources/static/css/report/baseReport.css
  src/main/resources/static/css/report/reportDetail.css
  src/main/resources/static/css/report/reportForm.css
  src/main/resources/static/css/report/reportList.css
  src/main/resources/static/css/user/admin.css
  src/main/resources/static/css/user/mainPageSearch.css
  src/main/resources/static/css/user/profile_edit.css
  src/main/resources/static/images/slideImage_1.png
  src/main/resources/templates/category/category_manage.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/discussion/d_create_form.html
  src/main/resources/templates/discussion/d_detail.html
  src/main/resources/templates/discussion/debate_list.html
  src/main/resources/templates/discussion/free_create_form.html
  src/main/resources/templates/discussion/freedcs_list.html
  src/main/resources/templates/home/main.html
  src/main/resources/templates/report/detail.html
  src/main/resources/templates/report/form.html
Labels: enhancement

#134 Enhancement/133
  src/main/java/com/example/coconut/CoconutApplication.java
  src/main/java/com/example/coconut/global/initData/Dev.java
  src/main/resources/static/css/user/admin.css
  src/main/resources/static/images/projectFunctionImage/coconut er다이어그램.png
  src/main/resources/static/images/projectFunctionImage/관리자 페이지.png
  src/main/resources/static/images/projectFunctionImage/나의 활동 페이지.png
  src/main/resources/static/images/projectFunctionImage/로그인 페이지.png
  src/main/resources/static/images/projectFunctionImage/마이 페이지.png
  src/main/resources/static/images/projectFunctionImage/메인 페이지.png
  src/main/resources/static/images/projectFunctionImage/문의하기 페이지.png
  src/main/resources/static/images/projectFunctionImage/자유 토론 페이지.png
  src/main/resources/static/images/projectFunctionImage/찬반 토론 페이지.png
  src/main/resources/static/images/projectFunctionImage/프로필 수정 페이지.png
  src/main/resources/templates/common/navbar.html
  src/main/resources/templates/report/base.html
  src/main/resources/templates/report/list.html
  src/test/java/com/example/coconut/CoconutApplicationTests.java
Labels: documentation

#136 Add files via upload
  src/main/resources/static/images/projectFunctionImage/검색 페이지.png
Labels: documentation
